### ISSUE TITLE
Uncaught boto3 exception in GOES

### ISSUE THREAD

**Issue by astrobokonon** [LowellObservatory/Camelot#2]
Noticed that the GIF died, took a look at the log and saw this:

```
2019-01-03 16:53:40,697 INFO     No new files downloaded so skipping all actions.
2019-01-03 16:53:40,697 INFO     Sleeping for 150 seconds...
2019-01-03 16:56:10,786 INFO     Looking for files!
2019-01-03 16:56:10,807 INFO     Querying:
2019-01-03 16:56:10,808 INFO     ABI-L2-CMIPC/2019/002/16/
2019-01-03 16:57:08,793 ERROR    Traceback (most recent call last):
2019-01-03 16:57:08,793 ERROR      File "/opt/conda/lib/python3.7/site-packages/urllib3/connection.py", line 171, in _new_conn
2019-01-03 16:57:08,794 ERROR    (self._dns_host, self.port), self.timeout, **extra_kw)
2019-01-03 16:57:08,794 ERROR      File "/opt/conda/lib/python3.7/site-packages/urllib3/util/connection.py", line 56, in create_connection
2019-01-03 16:57:08,794 ERROR    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
2019-01-03 16:57:08,794 ERROR      File "/opt/conda/lib/python3.7/socket.py", line 748, in getaddrinfo
2019-01-03 16:57:08,795 ERROR    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
2019-01-03 16:57:08,795 ERROR    socket
2019-01-03 16:57:08,796 ERROR    .
2019-01-03 16:57:08,796 ERROR    gaierror
2019-01-03 16:57:08,796 ERROR    :
2019-01-03 16:57:08,796 ERROR    [Errno -2] Name or service not known
2019-01-03 16:57:08,796 ERROR
During handling of the above exception, another exception occurred:
2019-01-03 16:57:08,796 ERROR    Traceback (most recent call last):
2019-01-03 16:57:08,796 ERROR      File "/opt/conda/lib/python3.7/site-packages/botocore/httpsession.py", line 258, in send
2019-01-03 16:57:08,797 ERROR    decode_content=False,
2019-01-03 16:57:08,797 ERROR      File "/opt/conda/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
2019-01-03 16:57:08,798 ERROR    _stacktrace=sys.exc_info()[2])
2019-01-03 16:57:08,798 ERROR      File "/opt/conda/lib/python3.7/site-packages/urllib3/util/retry.py", line 343, in increment
2019-01-03 16:57:08,798 ERROR    raise six.reraise(type(error), error, _stacktrace)
2019-01-03 16:57:08,798 ERROR      File "/opt/conda/lib/python3.7/site-packages/urllib3/packages/six.py", line 686, in reraise
2019-01-03 16:57:08,799 ERROR    raise value
2019-01-03 16:57:08,799 ERROR      File "/opt/conda/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
2019-01-03 16:57:08,800 ERROR    chunked=chunked)
2019-01-03 16:57:08,800 ERROR      File "/opt/conda/lib/python3.7/site-packages/urllib3/connectionpool.py", line 343, in _make_request
2019-01-03 16:57:08,800 ERROR    self._validate_conn(conn)
2019-01-03 16:57:08,800 ERROR      File "/opt/conda/lib/python3.7/site-packages/urllib3/connectionpool.py", line 849, in _validate_conn
2019-01-03 16:57:08,801 ERROR    conn.connect()
2019-01-03 16:57:08,801 ERROR      File "/opt/conda/lib/python3.7/site-packages/urllib3/connection.py", line 314, in connect
2019-01-03 16:57:08,802 ERROR    conn = self._new_conn()
2019-01-03 16:57:08,802 ERROR      File "/opt/conda/lib/python3.7/site-packages/urllib3/connection.py", line 180, in _new_conn
2019-01-03 16:57:08,802 ERROR    self, "Failed to establish a new connection: %s" % e)
2019-01-03 16:57:08,803 ERROR    urllib3.exceptions
2019-01-03 16:57:08,803 ERROR    .
2019-01-03 16:57:08,803 ERROR    NewConnectionError
2019-01-03 16:57:08,803 ERROR    :
2019-01-03 16:57:08,803 ERROR    <botocore.awsrequest.AWSHTTPSConnection object at 0x7fb9fb6382b0>: Failed to establish a new connection: [Errno -2] Name or service not known
2019-01-03 16:57:08,803 ERROR
During handling of the above exception, another exception occurred:
2019-01-03 16:57:08,803 ERROR    Traceback (most recent call last):
2019-01-03 16:57:08,803 ERROR      File "goes16aws_looper.py", line 292, in <module>
2019-01-03 16:57:08,804 ERROR    main(outdir, creds, forceDown=forceDownloads, forceRegen=forceRegenPlot)
2019-01-03 16:57:08,804 ERROR      File "goes16aws_looper.py", line 205, in main
2019-01-03 16:57:08,804 ERROR    timedelta=keephours, forceDown=forceDown)
2019-01-03 16:57:08,805 ERROR      File "/home/lig/Codes/GOESMcGOESface/goes16_aws.py", line 113, in GOESAWSgrab
2019-01-03 16:57:08,805 ERROR    for objs in todaydata:
2019-01-03 16:57:08,805 ERROR      File "/opt/conda/lib/python3.7/site-packages/boto3/resources/collection.py", line 83, in __iter__
2019-01-03 16:57:08,805 ERROR    for page in self.pages():
2019-01-03 16:57:08,805 ERROR      File "/opt/conda/lib/python3.7/site-packages/boto3/resources/collection.py", line 166, in pages
2019-01-03 16:57:08,806 ERROR    for page in pages:
2019-01-03 16:57:08,806 ERROR      File "/opt/conda/lib/python3.7/site-packages/botocore/paginate.py", line 255, in __iter__
2019-01-03 16:57:08,806 ERROR    response = self._make_request(current_kwargs)
2019-01-03 16:57:08,806 ERROR      File "/opt/conda/lib/python3.7/site-packages/botocore/paginate.py", line 332, in _make_request
2019-01-03 16:57:08,807 ERROR    return self._method(**current_kwargs)
2019-01-03 16:57:08,807 ERROR      File "/opt/conda/lib/python3.7/site-packages/botocore/client.py", line 320, in _api_call
2019-01-03 16:57:08,808 ERROR    return self._make_api_call(operation_name, kwargs)
2019-01-03 16:57:08,808 ERROR      File "/opt/conda/lib/python3.7/site-packages/botocore/client.py", line 610, in _make_api_call
2019-01-03 16:57:08,808 ERROR    operation_model, request_dict)
2019-01-03 16:57:08,809 ERROR      File "/opt/conda/lib/python3.7/site-packages/botocore/endpoint.py", line 102, in make_request
2019-01-03 16:57:08,809 ERROR    return self._send_request(request_dict, operation_model)
2019-01-03 16:57:08,809 ERROR      File "/opt/conda/lib/python3.7/site-packages/botocore/endpoint.py", line 136, in _send_request
2019-01-03 16:57:08,809 ERROR    success_response, exception):
2019-01-03 16:57:08,809 ERROR      File "/opt/conda/lib/python3.7/site-packages/botocore/endpoint.py", line 210, in _needs_retry
2019-01-03 16:57:08,810 ERROR    caught_exception=caught_exception, request_dict=request_dict)
2019-01-03 16:57:08,810 ERROR      File "/opt/conda/lib/python3.7/site-packages/botocore/hooks.py", line 356, in emit
2019-01-03 16:57:08,810 ERROR    return self._emitter.emit(aliased_event_name, **kwargs)
2019-01-03 16:57:08,811 ERROR      File "/opt/conda/lib/python3.7/site-packages/botocore/hooks.py", line 228, in emit
2019-01-03 16:57:08,811 ERROR    return self._emit(event_name, kwargs)
2019-01-03 16:57:08,811 ERROR      File "/opt/conda/lib/python3.7/site-packages/botocore/hooks.py", line 211, in _emit
2019-01-03 16:57:08,812 ERROR    response = handler(**kwargs)
2019-01-03 16:57:08,812 ERROR      File "/opt/conda/lib/python3.7/site-packages/botocore/retryhandler.py", line 183, in __call__
2019-01-03 16:57:08,812 ERROR    if self._checker(attempts, response, caught_exception):
2019-01-03 16:57:08,812 ERROR      File "/opt/conda/lib/python3.7/site-packages/botocore/retryhandler.py", line 251, in __call__
2019-01-03 16:57:08,813 ERROR    caught_exception)
2019-01-03 16:57:08,813 ERROR      File "/opt/conda/lib/python3.7/site-packages/botocore/retryhandler.py", line 277, in _should_retry
2019-01-03 16:57:08,813 ERROR    return self._checker(attempt_number, response, caught_exception)
2019-01-03 16:57:08,813 ERROR      File "/opt/conda/lib/python3.7/site-packages/botocore/retryhandler.py", line 317, in __call__
2019-01-03 16:57:08,814 ERROR    caught_exception)
2019-01-03 16:57:08,814 ERROR      File "/opt/conda/lib/python3.7/site-packages/botocore/retryhandler.py", line 223, in __call__
2019-01-03 16:57:08,814 ERROR    attempt_number, caught_exception)
2019-01-03 16:57:08,814 ERROR      File "/opt/conda/lib/python3.7/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
2019-01-03 16:57:08,815 ERROR    raise caught_exception
2019-01-03 16:57:08,815 ERROR      File "/opt/conda/lib/python3.7/site-packages/botocore/endpoint.py", line 179, in _get_response
2019-01-03 16:57:08,815 ERROR    http_response = self._send(request)
2019-01-03 16:57:08,815 ERROR      File "/opt/conda/lib/python3.7/site-packages/botocore/endpoint.py", line 223, in _send
2019-01-03 16:57:08,816 ERROR    return self.http_session.send(request)
2019-01-03 16:57:08,816 ERROR      File "/opt/conda/lib/python3.7/site-packages/botocore/httpsession.py", line 278, in send
2019-01-03 16:57:08,817 ERROR    raise EndpointConnectionError(endpoint_url=request.url, error=e)
2019-01-03 16:57:08,817 ERROR    botocore.exceptions
2019-01-03 16:57:08,817 ERROR    .
2019-01-03 16:57:08,817 ERROR    EndpointConnectionError
2019-01-03 16:57:08,817 ERROR    :
2019-01-03 16:57:08,818 ERROR    Could not connect to the endpoint URL: "https://noaa-goes16.s3.amazonaws.com/?prefix=ABI-L2-CMIPC%2F2019%2F002%2F16%2F&encoding-type=url"
```

Looks like I need better exception handling on the boto connection(s) to deal with internet dropouts! External connection monitor at the site went down at the same time as seen below:

![image](https://user-images.githubusercontent.com/1168555/50657809-c2b7b680-0f54-11e9-8308-0f266fb0205c.png)

**Comment by astrobokonon** [comment]
Attempting to quickly fix via 1d8d29aed8d301c996983f8576a83cae6b0a784c and 9b60f99e941d4c8ac4ce65e149a3e05c56da2357; now running with these in place to test for a little while before calling this close-able.

**Comment by astrobokonon** [comment]
Had to add in another; 733dfe2085be69baeea361fdcbf849526343f688.

Trying to catch the base class rather than each subclass of the ConnectionError but we'll see I guess.

**Comment by astrobokonon** [comment]
After a lengthy network connection interruption, it seems like this is the main failure reported:

```2019-02-18 09:45:06,425 INFO     QUERY FAILURE! EndpointConnectionError```

Which is pretty encouraging, didn't have to bounce the container when the network came back up.

**Comment by astrobokonon** [comment]
Content to close this now, will reopen if I see another failure mode that I'm not catching.
